# Generated by Django 4.2.16 on 2026-06-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invite_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
