# Generated by Django 4.2.16 on 2026-06-07 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('birthday', "Tug'ilgan kun"), ('wedding', "To'y kuni"), ('school_start', "O'qishga kirgan kun"), ('school_end', "O'qishni tugatgan kun"), ('death', 'Vafot etgan kun'), ('memorial', 'Xotira kuni'), ('other', 'Boshqa')], max_length=30)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='persons.person')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
