# Generated by Django 4.2.16 on 2026-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_place',
            field=models.CharField(blank=True, help_text="Tug'ilgan joy (viloyat, shahar)", max_length=200),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='type',
            field=models.CharField(choices=[('birthday', "Tug'ilgan kun"), ('wedding', "To'y / Nikoh"), ('school_start', "O'qishga kirish"), ('school_end', "O'qishni tugatish"), ('work_start', 'Ishga kirish'), ('work_end', 'Ishdan ketish'), ('military', 'Harbiy xizmat'), ('hajj', 'Haj / Umra'), ('award', 'Mukofot / Unvon'), ('move', "Ko'chib o'tish"), ('illness', 'Kasallik / Davolanish'), ('travel', 'Sayohat'), ('death', 'Vafot etgan kun'), ('memorial', 'Xotira kuni'), ('other', 'Boshqa')], max_length=30),
        ),
    ]
