# Generated by Django 4.2.16 on 2026-06-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_share_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='spouse',
        ),
    ]
