# Generated by Django 5.0.6 on 2026-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_add_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deceased',
            field=models.BooleanField(default=False, help_text="Vafot etganmi (sana ma'lum bo'lmasa ham)"),
        ),
    ]
